name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: windows-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2

      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: .\gradlew.bat build